#!/usr/bin/env python3
"""
Pushes a show generated by frames.mjs to the controller over BLE.

Deliberately dumb: it does no encoding of its own, so whatever lights up is
what @openboard/aurora-protocol produced. Chunking to MTU mirrors what the
mobile BLE layer will have to do.

    uv run --with bleak tools/send.py show.json
"""

import argparse
import asyncio
import json
import sys

from bleak import BleakClient, BleakScanner

NUS_RX = "6e400002-b5a3-f393-e0a9-e50e24dcca9e"

# Every Aurora-family mode the firmware can advertise as.
AURORA_NAMES = {
    "Aurora Board#1@3",
    "Kilter Board#1@3",
    "Tension Board#1@3",
    "Decoy Board#1@3",
    "Grasshopper Board#1@3",
}


async def find_board(address, timeout):
    if address:
        return address

    print(f"scanning {timeout}s for an Aurora-family board...", file=sys.stderr)
    devices = await BleakScanner.discover(timeout=timeout)

    for d in devices:
        if d.name in AURORA_NAMES:
            print(f"found {d.name} at {d.address}", file=sys.stderr)
            return d.address

    sys.exit("no board found; is it powered and not already connected elsewhere?")


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("show", help="JSON produced by frames.mjs")
    ap.add_argument("--address", help="skip scanning and connect to this address")
    ap.add_argument("--timeout", type=float, default=10.0)
    args = ap.parse_args()

    with open(args.show) as f:
        show = json.load(f)["show"]

    address = await find_board(args.address, args.timeout)

    async with BleakClient(address) as client:
        # The controller caps the ATT MTU at 23, so this lands at 20 bytes
        # whatever we ask for; the firmware reassembles across writes.
        chunk = max(20, client.mtu_size - 3)
        print(f"connected, mtu={client.mtu_size}, writing {chunk}B chunks\n", file=sys.stderr)

        for stepno, step in enumerate(show, 1):
            packets = [bytes.fromhex(p) for p in step["packets"]]
            total = sum(len(p) for p in packets)

            print(
                f"[{stepno}/{len(show)}] {step['name']}: {step['note']}\n"
                f"          {len(packets)} packet(s), {total} bytes",
                file=sys.stderr,
            )

            for packet in packets:
                for i in range(0, len(packet), chunk):
                    await client.write_gatt_char(NUS_RX, packet[i : i + chunk], response=False)
                    await asyncio.sleep(0.01)

            await asyncio.sleep(step["holdMs"] / 1000)

        print("\ndone", file=sys.stderr)


asyncio.run(main())
